services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT_NUMBER: 7077
      SPARK_MASTER_WEBUI_PORT_NUMBER: 8081
    ports:
      - "7077:7077"  # Spark Master port
      # - "8080:8080"  # Spark Web UI port
    networks:
      - internal_network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_PORT: 8082
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark Worker port
    networks:
      - internal_network

  spark-submit:
    image: bitnami/spark:latest
    container_name: spark-submit
    environment:
      SPARK_MODE: client
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    entrypoint: ["tail", "-f", "/dev/null"] # Placeholder for spark-submit jobs

networks:
  internal_network:
    external: true