services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ../../config/prometheus_config.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password, ganti pada saat deployment
    networks:
      - internal_network

networks:
  internal_network:
    external: true